'use strict';

// 由 build-auto-preferred.ts 按档位 CEFR 等级自动生成，不要手改 —— 改文章后重跑。
module.exports = {
  "original-w3-v-formation": ["aloft","ingenuity","reciprocal","migrate","collision","rotate","biologist","pelican","aerodynamic","vortex","logger","lightweight","swap","fairness","flap","curl"],
  "original-w3-container": ["congested","accelerated","tanker","tariff","cargo","brutal","acre","unremarkable","bale","sling","unload","sack","stack","dock","sail","deck"],
  "original-w3-marshmallow-test": ["children","token","cognitive","pretzel","marshmallow","temptation","distract","shrink","nursery","reverse","psychology","sensible","considerably","colleague","version","circumstance"],
  "original-w3-oral-rehydration": ["children","dehydration","zinc","sterile","intestine","shorten","scarce","drip","sodium","osmosis","cholera","glucose","bacterial","twentieth","according","vomit"],
  "original-w3-weather-forecast": ["meteorologist","imbalance","ensemble","earliest","printout","forecaster","rework","restart","richardson","simulation","according","compute","obey","beam","squeeze","sensible"],
  "original-w3-pencil": ["kiln","graphite","paste","grind","clay","monopoly","carbon","core"],
  "original-w3-polymer-notes": ["shred","polymer","forgery","fibre","flexible","energy"],
  "original-w3-vacuum-flask": ["convection","flask","vacuum","patent","glassblower","dewar","conduction","stopper","particle"],
  "original-w3-chilli-burn": ["mammal","sensor","protein","capsaicin","diluted","taster","unharmed","trader","extract","nerve","convert","panel","identify","pharmacist"],
  "original-w3-city-otters": ["sewer","reservoir","otter","waterway","homeowner","leash","territory","estate"],
  "original-w3-fish": ["tank","asleep","castle","count","whatever","plant","instead","send","last"],
  "original-w3-lunch-boxes": ["canteen","sticker","purpose","last"],
  "original-w3-wrong-list": ["notice","voice","understand","part","mistake","nobody","next","last"],
  "original-w3-boy-by-the-gates": ["bench","count","pass","gate","nobody","next","last"],
  "original-w3-tin-under-the-bed": ["snack","coin","secret","shut","plastic","plate","cost","fall","knock","shout","next"],
  "original-w3-understudy": ["rehearsal","costume","hook","corridor","cast","rehearse","understudy","halfway","fasten","afterward","loud","pause","whisper","silent","barely","aside"],
  "original-w3-trophy": ["crack","snap","cabinet","trophy","glue","forearm","sometime","honest","properly","recommend","slightly","finger","edge"],
  "original-w3-translating": ["pavement","wipe","community","halfway","disappoint","careless","sometime","flash","translate","prize","struggle","somehow","beat","edge","unless","term"],
  "original-w3-badminton": ["rally","shuttle","halfway","afterward","loud","somehow","properly","breath","score","beat","protect","worth"],
  "original-w3-spare-motor": ["clap","spare","trainer","shoebox","robot","afterward","stupid","motor","waste","tiny","finger","beat","edge","term","teammate","worth"],
  "original-w3-group-project": ["margin","label","panel","project","cardboard","glue","riverbank","handwriting","tighten","shallow","geography","presentation","tiny","suppose"],
  "original-w3-lunch-rush": ["chop","flame","wipe","hawker","cucumber","disappoint","queue","stall","fold","counter","finger","suddenly","suppose","secretly","rest"],
  "original-w3-question-jar": ["tablecloth","tortoise","groan","shark","drumstick","chopsticks","upside","polytechnic","handwriting","unfold","thumb","fold","loud","edge","pattern"],
  "original-w3-just-a-joke": ["tray","canteen","delete","underneath","breath","surround","sticker","rest"],
  "original-w3-twelve-moves": ["throat","puzzle","tire","term","able"],
};
